version: "3.5"
services:
  mysql:
    image: mysql:8.0.26
    environment:
      MYSQL_USER: myusr
      MYSQL_PASSWORD: Password1!
    container_name: "mysql-1"
    ports:
      - "3306:3306"
    networks:
      - sample-network
  postgresql:
    image: postgres:14.4
    environment:
      POSTGRESQL_DATABASE: orders
      POSTGRESQL_USER: myusr
      POSTGRESQL_PASSWORD: Password1!
    container_name: "postgresql-1"
    ports:
      - "5432:5432"
    networks:
      - sample-network
  schema-loader:
    image: ghcr.io/scalar-labs/scalardb-schema-loader:3.5.2
    container_name: "schema-loader-1"
    depends_on:
      - postgresql
      - mysql
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
      - ./database-docker.properties:/database.properties
      - ./schema.json:/schema.json
    entrypoint: /bin/bash
    command: /wait-for-it.sh -t 60 postgresql:5432 -- java -jar app.jar -f /schema.json --config /database.properties --replication-factor 1 --coordinator
    networks:
      - sample-network
    restart: on-failure
networks:
  sample-network:
    name: sample-network
